#pragma once
#define MARIO_WALKING_SPEED		0.2f
#define MARIO_FLY_SPEED		0.2f
#define MARIO_RUNNING_SPEED		0.3f
#define MARIO_JUMP_SPEED		0.9f

#define MARIO_ACCEL_WALK_X	0.002f
#define MARIO_ACCEL_RUN_X	0.003f
#define MARIO_ACCEL_JUMP_Y	0.009f
#define MARIO_ACCEL_RUN_JUMP_Y	0.05f
#define MARIO_ACCEL_FLY_X	0.006f
#define MARIO_ACCEL_FLY_Y	0.006f

#define MARIO_JUMP_SPEED_Y		0.5f
#define MARIO_FLY_SPEED_Y		0.05f
#define MARIO_JUMP_RUN_SPEED_Y	0.6f

#define MARIO_GRAVITY			0.002f
#define MARIO_FRICTION          0.00035f      
#define MARIO_JUMP_DEFLECT_SPEED  0.009f
#define MARIO_MAX_VY            0.15f

#define MARIO_STATE_DIE				-10
#define MARIO_STATE_IDLE			0
#define MARIO_STATE_WALKING_RIGHT	100
#define MARIO_STATE_WALKING_LEFT	200

#define MARIO_STATE_JUMP			300
#define MARIO_STATE_HIGH_JUMP			309
#define MARIO_STATE_RELEASE_JUMP    301

#define MARIO_STATE_FLY_RIGHT			302
#define MARIO_STATE_FLY_LEFT			303

#define MARIO_STATE_RUNNING_RIGHT	400
#define MARIO_STATE_RUNNING_LEFT	500

#define MARIO_STATE_SIT				600
#define MARIO_STATE_SIT_RELEASE		601

#define MARIO_STATE_WALK	101
#define MARIO_STATE_RUN	501
#define MARIO_STATE_FALL	502
#define MARIO_STATE_SKID	503
#define MARIO_STATE_FLY			504

#pragma endregion

#define GROUND_Y 160.0f
#define MAX_ENERGY 40




#define	MARIO_LEVEL_SMALL	1
#define	MARIO_LEVEL_BIG		2
#define MARIO_LEVEL_RACCOON 3

#define MARIO_BIG_BBOX_WIDTH  14*3
#define MARIO_BIG_BBOX_HEIGHT 27*3 
#define MARIO_BIG_SITTING_BBOX_WIDTH  14*3
#define MARIO_BIG_SITTING_BBOX_HEIGHT 16*3

#define MARIO_SIT_HEIGHT_ADJUST ((MARIO_BIG_BBOX_HEIGHT-MARIO_BIG_SITTING_BBOX_HEIGHT)/2)

#define MARIO_SMALL_BBOX_WIDTH  13*3
#define MARIO_SMALL_BBOX_HEIGHT 13*3


#define MARIO_UNTOUCHABLE_TIME 2000

#define ANI_MARIO_LEVEL_SMALL "ani-small-mario"
#define ANI_MARIO_LEVEL_BIG "ani-big-mario"
#define ANI_MARIO_LEVEL_RACCOON "ani-raccoon-mario"


#define ANI_MARIO_STATE_IDLE "idle"
#define ANI_MARIO_STATE_RUN_JUMP "high-jump"
#define ANI_MARIO_STATE_WALK_JUMP "jump"
#define ANI_MARIO_STATE_SIT "crouch"
#define ANI_MARIO_STATE_SKID "skid"
#define ANI_MARIO_STATE_KICK "kick"
#define ANI_MARIO_STATE_HOLD "hold"
#define ANI_MARIO_STATE_RUN "run"
#define ANI_MARIO_STATE_WALK "walk"
#define ANI_MARIO_STATE_FLY "fly"
#define ANI_MARIO_STATE_FALL "fall"
#define ANI_MARIO_STATE_DIE "die"
